version: '3.9'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    #restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    #restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  app:
    image: nextcloud:apache
    #restart: always
    ports:
      - 8080:80
      - 8090:443
    volumes:
      - nextcloud:/var/www/html
      - config:/var/www/html/config
      - apps:/var/www/html/custom_apps
      - data:/var/www/html/data
      - dlna:/var/www/html/dlna
    environment:
      - PROXY_LOCATION=${NEXTCLOUD_PROXY_LOCATION}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT= 8080,8090
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - MYSQL_HOST=${MYSQL_HOST}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  cron:
    image: nextcloud:apache
    #restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  proxy:
    build: ./proxy
    #restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    environment:
      DEFAULT_HOST: pihole.imadjamil.lan
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    #restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  pihole:
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '8053:80/tcp'
      - '8054:443/tcp'
    volumes:
      - pihole:/etc/pihole/
      - dnsmasq.d:/etc/dnsmasq.d/
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    environment:
      - ServerIP=${SERVER_IP}
      - "PROXY_LOCATION:pihole"
      - "VIRTUAL_HOST:pihole.imadjamil.lan"
      - "VIRTUAL_PORT:8053"
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
      # LAN hostnames for other docker containers using jwilder
      - 'imadjamil.lan:192.168.1.6'
      - 'ghost ghost.imadjamil.lan:192.168.1.6'
      - 'pihole pihole.imadjamil.lan:192.168.1.6'
      - 'app nextcloud.imadjamil.lan:192.168.1.6'
      - 'emonpi emonpi.imadjamil.lan:192.168.1.207'
    #restart: always

  ghost:
    image: fractalf/ghost
    ports:
      - '2368:2368/tcp'
    volumes:
      - ghost:/ghost-override
    environment:
      PROXY_LOCATION: ghost
      VIRTUAL_HOST: ghost.imadjamil.lan
      VIRTUAL_PORT: 2368
      NODE_ENV: development
    #restart: always

volumes:
  ghost:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/ghost'
  dnsmasq.d:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/pihole/dnsmasq.d'
  pihole:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/pihole/pihole'
  dlna:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/dlna_media'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/nextcloud/db'
  nextcloud:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/nextcloud/nextcloud'
  config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/nextcloud/config'
  apps:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/nextcloud/apps'
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/nextcloud/data'
  certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/nextcloud/certs'
  vhost.d:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/nextcloud/vhost.d'
  html:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/md0/nextcloud/html'

networks:
  proxy-tier:
